---
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
branches:
  only:
    - master
skip_tags: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
configuration: Release
image: "Visual Studio 2017"
nuget:
  disable_publish_on_pr: true
version: "0.0.1.{build}"
